# Generated by Django 2.2.5 on 2019-10-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='学生',
            name='学生性别',
            field=models.CharField(default='女', max_length=12),
        ),
    ]
