# Generated by Django 2.2.5 on 2019-10-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0002_学生_学生性别'),
    ]

    operations = [
        migrations.AddField(
            model_name='学生',
            name='学生生日',
            field=models.DateTimeField(default='2010-10-01'),
            preserve_default=False,
        ),
    ]
