# Generated by Django 2.2.5 on 2019-10-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0003_学生_学生生日'),
    ]

    operations = [
        migrations.CreateModel(
            name='库存',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('物品名称', models.CharField(max_length=50)),
                ('物品类别', models.CharField(max_length=30)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '仓库',
            },
        ),
        migrations.AlterModelOptions(
            name='优惠券',
            options={'verbose_name_plural': '优惠券'},
        ),
        migrations.AlterModelOptions(
            name='优惠券使用',
            options={'verbose_name_plural': '优惠券使用'},
        ),
        migrations.AlterModelOptions(
            name='学生',
            options={'verbose_name_plural': '学生'},
        ),
        migrations.AlterModelOptions(
            name='家长联系方式',
            options={'verbose_name_plural': '家长联系方式'},
        ),
        migrations.AlterModelOptions(
            name='班',
            options={'verbose_name_plural': '班'},
        ),
        migrations.AlterModelOptions(
            name='班级分配',
            options={'verbose_name_plural': '班级分配'},
        ),
        migrations.AlterModelOptions(
            name='缴费',
            options={'verbose_name_plural': '缴费'},
        ),
        migrations.AlterModelOptions(
            name='老师',
            options={'verbose_name_plural': '老师'},
        ),
        migrations.AlterModelOptions(
            name='课程',
            options={'verbose_name_plural': '课程'},
        ),
        migrations.CreateModel(
            name='出库记录',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('出库时间', models.DateTimeField(auto_now_add=True)),
                ('出库单价', models.DecimalField(decimal_places=2, max_digits=7)),
                ('备注', models.TextField(blank=True)),
                ('关联缴费', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infoManage.缴费')),
                ('出库物品', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infoManage.库存')),
            ],
            options={
                'verbose_name_plural': '出库记录',
            },
        ),
        migrations.CreateModel(
            name='入库记录',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('入库时间', models.DateTimeField(auto_now_add=True)),
                ('入库单价', models.DecimalField(decimal_places=2, max_digits=7)),
                ('备注', models.TextField(blank=True)),
                ('入库物品', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infoManage.库存')),
            ],
            options={
                'verbose_name_plural': '入库记录',
            },
        ),
    ]
