# Generated by Django 2.2.5 on 2019-10-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0004_auto_20191011_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='学生',
            name='学生性别',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=12),
        ),
        migrations.CreateModel(
            name='课程表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('上课教室', models.CharField(max_length=20)),
                ('备注', models.TextField(blank=True)),
                ('上课班次', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoManage.班')),
            ],
            options={
                'verbose_name_plural': '课程表',
            },
        ),
    ]
