# Generated by Django 2.2.5 on 2019-10-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0006_auto_20191015_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='家长联系方式',
            name='与学生关系',
            field=models.CharField(blank=True, choices=[('爸爸', '爸爸'), ('妈妈', '妈妈'), ('爷爷', '爷爷'), ('奶奶', '奶奶'), ('姥姥', '姥姥'), ('姥爷', '姥爷'), ('哥哥', '哥哥'), ('姐姐', '姐姐'), ('姑姑', '姑姑'), ('姑父', '姑父'), ('姨', '姨'), ('姨夫', '姨夫'), ('其他直系亲属', '其他直系亲属'), ('其他关系', '其他关系')], max_length=20),
        ),
    ]
