# Generated by Django 2.2.5 on 2019-10-17 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0007_auto_20191016_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='备注',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('备注类型', models.CharField(choices=[('学生备注', '学生备注'), ('缴费备注', '缴费备注'), ('优惠券备注', '优惠券备注'), ('优惠券使用备注', '优惠券使用备注'), ('家长联系方式备注', '家长联系方式备注'), ('课程备注', '课程备注'), ('班备注', '班备注'), ('班级分配备注', '班级分配备注'), ('老师备注', '老师备注'), ('库存备注', '库存备注'), ('入库记录备注', '入库记录备注'), ('出库记录备注', '出库记录备注')], max_length=10)),
                ('备注关联id', models.IntegerField()),
                ('备注', models.TextField()),
            ],
            options={
                'verbose_name_plural': '备注',
            },
        ),
        migrations.AddField(
            model_name='入库记录',
            name='入库数量',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='出库记录',
            name='出库数量',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='库存',
            name='库存数量',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='班级分配',
            name='上课日期',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='班级分配',
            name='结课日期',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='课程表',
            name='上课时间',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='课程表',
            name='下课时间',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
