# Generated by Django 2.2.5 on 2019-10-17 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0008_auto_20191017_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='备注',
            name='备注时间',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
