# Generated by Django 2.2.5 on 2019-10-17 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0009_备注_备注时间'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='优惠券',
            name='关联手机号',
        ),
        migrations.AddField(
            model_name='优惠券使用',
            name='关联手机号',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='优惠券使用',
            name='缴费单号',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='infoManage.缴费'),
        ),
    ]
