# Generated by Django 2.2.5 on 2019-10-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0010_auto_20191017_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='优惠券',
            old_name='备注',
            new_name='优惠券介绍',
        ),
    ]
