# Generated by Django 2.2.5 on 2019-10-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0012_auto_20191017_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='缴费',
            name='缴费编号',
            field=models.IntegerField(default=None, unique=True, null=True),
            preserve_default=False,
        ),
    ]
