# Generated by Django 2.2.5 on 2019-10-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0013_缴费_缴费编号'),
    ]

    operations = [
        migrations.AlterField(
            model_name='缴费',
            name='缴费编号',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
