# Generated by Django 2.2.5 on 2019-10-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0016_auto_20191025_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='优惠券使用',
            name='优惠券编号',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infoManage.优惠券'),
        ),
    ]
